FROM openjdk:latest
WORKDIR /usr/src/app
COPY /lesson3/out/artifacts/03_jar/03.jar .
CMD ["java", "-jar", "03.jar"]

#docker build -t my_image_name .
#docker run --name my_container_name my_image_name
